### ISSUE TITLE
Ejecutar game.py

### ISSUE THREAD

**Issue by Javierestevezz** [ringa-tech/juego-python-ia-misiles#3]
Al ejecutar game.py aparece la ventana inicial por muy poco tiempo y se cierra, ¿Qué puedo hacer? Solo lo descargué, abrí la carpeta en Visual Studio Code y al ejecutarlo eso.
Gracias

**Comment by ringa-tech** [comment]
Hola, debes ejecutar app.py en lugar de game.py, en el readme agregué el comando. Me dices si con eso tampoco funciona por favor

**Comment by ringa-tech** [comment]
Cerraré el incidente porque tiene tiempo sin respuesta. Si se presenta de nuevo, favor de abrir otro.
