### ISSUE TITLE
Error: division by zero (en Game.py linea 245)

### ISSUE THREAD

**Issue by Adrianqpr** [ringa-tech/juego-python-ia-misiles#4]
Hola Ringa-Tech. Me respondiste en YouTube "Ya hay un PR en el repositorio con la corrección. Pasa con algunas webcams. Si no conoces como tomar la corrección del PR, la subo al repo principal en unas horas". Tres preguntas:
 ¿a qué llamas PR?
¿Puede ser que da error porque no configuré la cámara web para los localizar los puntos en la cara para mover el cohete?
¿Subiste en el repositorio la corrección?

**Comment by ringa-tech** [comment]
Hola, me refiero a "Pull Request", una funcionalida de Github en la que otras personas pueden aportar código o correcciones.
Ya hice Merge de uno de los PR al repositorio principal, entonces si lo bajas de nuevo, probablemente ya te funciona. Podrías probar?

Si ya lo habías bajado y no lo quieres bajar de nuevo, entonces haz "git pull". Pero si no usas git comunmente puedes simplemente borrarlo y descargarlo de nuevo.
Me avisas si te funciona o si te sigue fallando

**Comment by Adrianqpr** [comment]
Ahora funciona muy bien, muchas gracias.
